font_family MesloLGS NF Regular
bold_font MesloLGS NF Bold
italic_font MesloLGS NF Italic
bold_italic_font MesloLGS NF Bold Italic
font_size 11.0
cursor_beam_thickness 9
cursor_stop_blinking_after 0
scrollback_lines 5000
scrollback_fill_enlarged_window yes
url_style double
open_url_with default
detect_urls yes
copy_on_select yes
window_border_width 2pt
inactive_text_alpha 1
confirm_os_window_close 2
tab_bar_style fade
tab_fade 0.35 0.7 1
tab_powerline_style slanted
background_opacity 1
editor micro
update_check_interval 0
allow_hyperlinks yes
shell_integration enabled
map f1 clear_terminal clear active

background #000000
foreground #FFFFFF

selection_background #33467C
selection_foreground #C0CAF5
url_color #73DACA

# Tabs
active_tab_background #6943FF
#tab_bar_background #000000

# normal
color0 #000000
color1 #D52822
color2 #3DB72A
color3 #FAD000
color4 #6943FF
color5 #FF628C
color6 #9EFFFF
color7 #DBDBE0

# bright
color8 #5C5C61
color9 #FF000D
color10 #3AD900
color11 #FAD000
color12 #6943FF
color13 #FF628C
color14 #9EFFFF
color15 #FFFFFF

# extended colors
color16 #FF9E68
color17 #DB4B4B
